// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package telebotrpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// TelebotClient is the client API for Telebot service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TelebotClient interface {
	Send(ctx context.Context, in *TelegramMessage, opts ...grpc.CallOption) (*TelegramSent, error)
}

type telebotClient struct {
	cc grpc.ClientConnInterface
}

func NewTelebotClient(cc grpc.ClientConnInterface) TelebotClient {
	return &telebotClient{cc}
}

func (c *telebotClient) Send(ctx context.Context, in *TelegramMessage, opts ...grpc.CallOption) (*TelegramSent, error) {
	out := new(TelegramSent)
	err := c.cc.Invoke(ctx, "/telebotrpc.Telebot/Send", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TelebotServer is the server API for Telebot service.
// All implementations must embed UnimplementedTelebotServer
// for forward compatibility
type TelebotServer interface {
	Send(context.Context, *TelegramMessage) (*TelegramSent, error)
	mustEmbedUnimplementedTelebotServer()
}

// UnimplementedTelebotServer must be embedded to have forward compatible implementations.
type UnimplementedTelebotServer struct {
}

func (UnimplementedTelebotServer) Send(context.Context, *TelegramMessage) (*TelegramSent, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Send not implemented")
}
func (UnimplementedTelebotServer) mustEmbedUnimplementedTelebotServer() {}

// UnsafeTelebotServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TelebotServer will
// result in compilation errors.
type UnsafeTelebotServer interface {
	mustEmbedUnimplementedTelebotServer()
}

func RegisterTelebotServer(s grpc.ServiceRegistrar, srv TelebotServer) {
	s.RegisterService(&_Telebot_serviceDesc, srv)
}

func _Telebot_Send_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TelegramMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TelebotServer).Send(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/telebotrpc.Telebot/Send",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TelebotServer).Send(ctx, req.(*TelegramMessage))
	}
	return interceptor(ctx, in, info, handler)
}

var _Telebot_serviceDesc = grpc.ServiceDesc{
	ServiceName: "telebotrpc.Telebot",
	HandlerType: (*TelebotServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Send",
			Handler:    _Telebot_Send_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "RPC-interface/telebot/telebot.proto",
}
